
name: Merge DEV to PROD

on:
  push:
    branches:
      - DEV

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PROD branch
      uses: actions/checkout@v3
      with:
        ref: PROD
        checkout: true

    - name: Merge DEV into PROD
      run: |
        git merge DEV
        
    - name: Push changes to PROD
      uses: actions/github-script@main
      with:
        script: |
          git push origin PROD
